// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

// WATER
export const WATER_FETCH = 'WATER_FETCH';
export const WATER_ERROR = 'WATER_ERROR';
export const ADD_WATER_FORM = 'ADD_WATER_CONST';

// USERS
export const USER_FETCH = 'USER_FETCH';
export const USER_ERROR = 'USER_ERROR';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

// PERMITS
export const PERMITS_SUCCESS = 'PERMITS_SUCCESS';
export const PERMITS_FETCH = 'PERMITS_FETCH';
export const PERMITS_ERROR = 'PERMITS_ERROR';
