// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

// WATER
export const WATER_FETCH = 'WATER_FETCH';
export const WATER_ERROR = 'WATER_ERROR';
export const ADD_WATER_FORM = 'ADD_WATER_FORM';
export const EDIT_WATER_SUCCESS = 'EDIT_SUCCESS';

// ENVIROMENT
export const ENVIRONMENT_FETCH = 'ENVIRONMENT_FETCH';
export const ENVIRONMENT_ERROR = 'ENVIRONMENT_ERROR';
export const ADD_ENVIRONMENT_FORM = 'ADD_ENVIRONMENT_FORM';
export const EDIT_ENVIRONMENT_SUCCESS = 'EDIT_ENVIRONMENT_SUCCESS';

// BIODIVERSITY
export const BIODIVERSITY_FETCH = 'BIODIVERSITY_FETCH';
export const BIODIVERSITY_ERROR = 'BIODIVERSITY_ERROR';
export const ADD_BIODIVERSITY_FORM = 'ADD_BIODIVERSITY_FORM';
export const EDIT_BIODIVERSITY_SUCCESS = 'EDIT_BIODIVERSITY_SUCCESS';

// SOIL
export const SOIL_FETCH = 'SOIL_FETCH';
export const SOIL_ERROR = 'SOIL_ERROR';
export const ADD_SOIL_FORM = 'ADD_SOIL_FORM';
export const EDIT_SOIL_SUCCESS = 'EDIT_SUCCESS';

// PRODUCTION
export const PRODUCTION_FETCH = 'PRODUCTION_FETCH';
export const PRODUCTION_ERROR = 'PRODUCTION_ERROR';
export const ADD_PRODUCTION_FORM = 'ADD_PRODUCTION_FORM';
export const EDIT_PRODUCTION_SUCCESS = 'EDIT_SUCCESS';

// CLIMATE
export const CLIMATE_FETCH = 'CLIMATE_FETCH';
export const CLIMATE_ERROR = 'CLIMATE_ERROR';
export const ADD_CLIMATE_FORM = 'ADD_CLIMATE_FORM';
export const EDIT_CLIMATE_SUCCESS = 'EDIT_SUCCESS';

// FAVOURITES
export const FETCH_FAVOURITES = 'FETCH_FAVOURITEs';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const DELETE_FAVOURITES = 'DELETE_FAVOURITES';

// USERS
export const USERS_FETCH = 'USERS_FETCH';
export const USER_ERROR = 'USER_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

// PERMITS
export const PERMITS_SUCCESS = 'PERMITS_SUCCESS';
export const PERMITS_FETCH = 'PERMITS_FETCH';
export const PERMITS_ERROR = 'PERMITS_ERROR';
